# SETUP
baseurl = "https://hugo-comments.netlify.com/"
publishdir = "public"
DefaultContentLanguage = "en"
#canonifyUrls = "true"
googleAnalytics = ""
disableKinds = ["RSS","taxonomy","taxonomyTerm","sitemap"] #remove this when blog goes live
summaryLength = 40

[params]
    author = "squdme"
    title = "Squd.me: Greet your friends."
    description = "Hello world squd.me."
    DateForm = "02.01.2006"
